---

- name : Download fat jar from nexus
  maven_artifact:
     group_id: demo
     artifact_id: demo
     repository_url: http://10.38.204.61:8081/#browse/browse:maven-releases	
     username: admin
     password: admin
     dest: /tmp/demo-1.0.jar

- name: Copy application WAR file to host
  copy:
    src: /tmp/demo-1.0.jar
    dest: /usr/share/jboss-as/standalone/deployments/

- name: Deploy fat jar to JBoss
  jboss:
    deploy_path: /usr/share/jboss-as/standalone/deployments/
    src: /tmp/demo-1.0.jar
    deployment: demo-1.0.jar
    state: present
