---
- name: Install OpenJDK 8
  become: true
  apt:
    pkg: openjdk-8-jdk
    state: present
    force: yes
    cache_valid_time: 3600
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2
